version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:v1.15.3
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333" # Porta gRPC
      - "6334:6334" # Porta REST
    volumes:
      - qdrant-storage:/qdrant/storage

volumes:
  qdrant-storage: